# 单机版配置
spring:
  application:
    name: ad-eureka

server:
  port: 8001

eureka:
  instance:
    hostname: eureka-server1
  client:
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据,所以设置为false
    fetch-registry: false
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 集群配置
---
spring:
  application:
    name: ad-eureka
  profiles: eureka-server1
server:
  port: 8001
eureka:
  instance:
    hostname: eureka-server1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server2:8002/eureka/,http://eureka-server3:8003/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: eureka-server2
server:
  port: 8002
eureka:
  instance:
    hostname: eureka-server2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/,http://eureka-server3:8003/eureka/

---
spring:
  application:
    name: ad-eureka
  profiles: eureka-server3
server:
  port: 8003
eureka:
  instance:
    hostname: eureka-server3
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/,http://eureka-server2:8002/eureka/