server:
  port: 8100
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://192.168.19.128:3306/zkyne_advert?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Zkyne_3618
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8001/eureka/
